### ISSUE TITLE
Feature Request: try `until`

### ISSUE THREAD

**Issue by eddieajau** [code-vicar/retry-if#1]
Found this library at just the right time for a project so thanks very much. We have a retry "window" requirement with a customer, so I was wondering if you would entertain adding a configuration option to be able to try "until" a moment in time (probably the millisecond epoch) after which it will throw errors normally.

If so, or if you have a better suggestion, I'm happy to do the coding for that.

Thanks in advance.

**Comment by code-vicar** [comment]
That's an interesting use case.

How about this: add an option to the constructor named 'deadline' which is an epoch time at which the library will stop retrying.

The other options will still be respected, so if the options specify a growing back-off it will continue to grow until either the max retries are hit or until the deadline is hit whichever comes first.

Right now the 'max retry' must still be provided, it isn't set up to allow indefinite retries.  If that's something that you'd need let me know.

**Comment by eddieajau** [comment]
`options.deadline` sounds like a plan to me. How can I help?

**Comment by code-vicar** [comment]
I'll probably have some time this week to implement it or, if you would rather take a crack at it, fork this project and work on it in a feature branch.  Let me know if you want to do that.  Once it's complete make a pull request and I'll review, don't forget about the tests too.  Use the npm scripts to build and run tests.

**Comment by code-vicar** [comment]
The deadline option has been added as of version v1.1.0.
For final usage example see the readme, thanks.
